# Parsing Schuylkill County Election results

The following notebook parses the archived 2018 precinct level election results from Schuylkill County from plain text into a dataframe (spreadsheet like data structure) to be used for matching.

Steps:

1. Copy the plain text data from Schuylkill County's [website]( https://www.co.schuylkill.pa.us/info/Offices/Election/Election/Results/Info.csp?Election=64)
2. Store the table as a  text locally at `schuylkill.csv`
4. Use this script to parse the primitive csv into a csv matching Open Elections style for its statewide precinct level resutls. 
5. Store the resulting file locally at `schuylkill_county_parsed.csv`

In [2]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'/Users/baxterdemers/pa-2018/parsing_election_results/schuylkill'

In [3]:
df = pd.read_csv('schuylkill.csv')
df.head()

           Precinct  Votes Denny Wolff  Dan Meuser  Write-in
0               NaN    NaN  Democratic  Republican       NaN
1  Ashland 1st Pct.  405.0         198         207       0.0
2  Ashland 2nd Pct.  353.0         136         217       0.0
3       Blythe Twp.  331.0         146         184       1.0
4       Branch Twp.  696.0         349         347       0.0

In [4]:
df = df[df.index > 0]
df.head()

                Precinct  Votes Denny Wolff Dan Meuser  Write-in
1       Ashland 1st Pct.  405.0         198        207       0.0
2       Ashland 2nd Pct.  353.0         136        217       0.0
3            Blythe Twp.  331.0         146        184       1.0
4            Branch Twp.  696.0         349        347       0.0
5  Butler Twp. Englewood  245.0          89        156       0.0

In [5]:
candidate_to_party = {
    'Denny Wolff':'Democratic', 
    'Dan Meuser':'Republican', 
    'Write-in':np.nan,
}

In [6]:
output = pd.DataFrame(columns=['county', 'precinct', 'office', 'district', 'candidate', 'party','votes', 'absentee', 'election_day'])
unpivoted = pd.melt(df, id_vars='Precinct', value_vars=['Denny Wolff', 'Dan Meuser', 'Write-in'], var_name='candidate', value_name='votes')
output = output.append(unpivoted.rename(columns={'Precinct':'precinct'}))
output.county = 'Schuylkill'
output.district = 9
output.office = 'U.S. House'
output.party = output.candidate.map(candidate_to_party)
output.head()

,county,precinct,office,district,candidate,party,votes,absentee,election_day
0,Schuylkill,Ashland 1st Pct.,U.S. House,9,Denny Wolff,Democratic,198,NaN,NaN
1,Schuylkill,Ashland 2nd Pct.,U.S. House,9,Denny Wolff,Democratic,136,NaN,NaN
2,Schuylkill,Blythe Twp.,U.S. House,9,Denny Wolff,Democratic,146,NaN,NaN
3,Schuylkill,Branch Twp.,U.S. House,9,Denny Wolff,Democratic,349,NaN,NaN
4,Schuylkill,Butler Twp. Englewood,U.S. House,9,Denny Wolff,Democratic,89,NaN,NaN

In [7]:
output.party.unique()

array(['Democratic', 'Republican', nan], dtype=object)

In [8]:
output.head(20)

,county,precinct,office,district,candidate,party,votes,absentee,election_day
0,Schuylkill,Ashland 1st Pct.,U.S. House,9,Denny Wolff,Democratic,198,NaN,NaN
1,Schuylkill,Ashland 2nd Pct.,U.S. House,9,Denny Wolff,Democratic,136,NaN,NaN
2,Schuylkill,Blythe Twp.,U.S. House,9,Denny Wolff,Democratic,146,NaN,NaN
3,Schuylkill,Branch Twp.,U.S. House,9,Denny Wolff,Democratic,349,NaN,NaN
4,Schuylkill,Butler Twp. Englewood,U.S. House,9,Denny Wolff,Democratic,89,NaN,NaN
5,Schuylkill,Butler Twp. Ft. Springs,U.S. House,9,Denny Wolff,Democratic,251,NaN,NaN
6,Schuylkill,Butler Twp. Lavelle,U.S. House,9,Denny Wolff,Democratic,198,NaN,NaN
7,Schuylkill,Butler Twp. Northeast,U.S. House,9,Denny Wolff,Democratic,53,NaN,NaN
8,Schuylkill,Cass Twp. North,U.S. House,9,Denny Wolff,Democratic,73,NaN,NaN
9,Schuylkill,Cass Twp. South,U.S. House,9,Denny Wolff,Democratic,231,NaN,NaN
10,Schuylkill,Delano Twp.,U.S. House,9,Denny Wolff,Democratic,60,NaN,NaN
11,Schuylkill,East Norwegian Twp.,U.S. House,9,Denny Wolff,Democratic,193,NaN,NaN
12,Schuylkill,Frackville North,U.S. House,9,Denny Wolff,Democratic,161,NaN,NaN
13,Schuylkill,Frackville Middle,U.S. House,9,Denny Wolff,Democratic,126,NaN,NaN
14,Schuylkill,Frackville South,U.S. House,9,Denny Wolff,Democratic,260,NaN,NaN
15,Schuylkill,Gilberton,U.S. House,9,Denny Wolff,Democratic,104,NaN,NaN
16,Schuylkill,Girardville,U.S. House,9,Denny Wolff,Democratic,187,NaN,NaN
17,Schuylkill,Gordon,U.S. House,9,Denny Wolff,Democratic,131,NaN,NaN
18,Schuylkill,Mahanoy City Pct. 1,U.S. House,9,Denny Wolff,Democratic,60,NaN,NaN
19,Schuylkill,Mahanoy City Pct. 2,U.S. House,9,Denny Wolff,Democratic,147,NaN,NaN

In [8]:
output.to_csv('schuylkill_county_parsed.csv',index=False)